function [sensitivity_objective_function_value, sensitivity_volume_fraction] = sensivity_filter( ...
    x, ...
    sensitivity_objective_function_value, ...
    sensitivity_volume_fraction, ...
    H, ...
    Hs, ...
    senitivity_filter_class ...
)
    % filter class: [1, 2]
    % - 1: sensitivity filter
    % - 2: density filter

    if senitivity_filter_class == 1
        sensitivity_objective_function_value(:) = H * (x(:) .* sensitivity_objective_function_value(:)) ./ Hs ./ max(1e-3, x(:));
    elseif senitivity_filter_class == 2
        sensitivity_objective_function_value(:) = H * (sensitivity_objective_function_value(:) ./ Hs);
    end

    sensitivity_volume_fraction(:) = H * (sensitivity_volume_fraction(:) ./ Hs);
end