function [ ...
    constraint_number, ...
    variable_number, ...
    x_min, ...
    x_max, ...
    x_old_1, ...
    x_old_2, ...
    asymptote_lower_bound, ...
    asymptote_upper_bound, ...
    a_0, ...
    a_i, ...
    c_mma, ...
    d ...
] = init_mma_parameters(x, nel_x, nel_y, is_spring)
    if is_spring
        constraint_number = 3;
%         a_i = zeros(constraint_number, 1);
        a_i = [1 0 0]' ;
    else
        constraint_number = 1;
        a_i = zeros(constraint_number, 1);
    end
    
    variable_number = nel_x * nel_y;
    
    x_min = zeros(variable_number, 1);
    x_max = ones(variable_number, 1);
    
    x_old_1 = x(:);
    x_old_2 = x(:);
    
    asymptote_lower_bound = zeros(variable_number, 1);
    asymptote_upper_bound = ones(variable_number, 1);
    
    a_0 = 1;
    
    c_mma = 2000 * ones(constraint_number, 1);
    d = ones(constraint_number, 1);
end