function [ ...
    constraint_number, ...
    element_number, ...
    x_min, ...
    x_max, ...
    x_old_1, ...
    x_old_2, ...
    lower_asymptotes, ...
    upper_asymptotes, ...
    a_0, ...
    a, ...
    c_mma, ...
    d ...
] = init_mma_parameters(x, nel_x, nel_y)
    constraint_number = 1;
    element_number = nel_x * nel_y;
    
    x_min = zeros(element_number, 1);
    x_max = ones(element_number, 1);
    
    x_old_1 = x(:);
    x_old_2 = x(:);
    
    lower_asymptotes = ones(element_number, 1);
    upper_asymptotes = ones(element_number, 1);
    
    a_0 = 1;

    a = zeros(constraint_number, 1);
    c_mma = 10000 * ones(constraint_number, 1);
    d = zeros(constraint_number, 1);
end